CREATE TABLE IF NOT EXISTS questionary
(
    id bigserial,
    _sys_terminalid     VARCHAR,
    _sys_resellerid     VARCHAR,
    _sys_merchantid     VARCHAR,
    pos_id              VARCHAR,
    psp_version         VARCHAR,
    enable_cashier_mode VARCHAR,
    _eventtime timestamptz,
    question1           VARCHAR,
    answer1             VARCHAR,
    question2           VARCHAR,
    answer2             VARCHAR,
    question3           VARCHAR,
    answer3             VARCHAR,
    question4           VARCHAR,
    answer4             VARCHAR,
    question5           VARCHAR,
    answer5             VARCHAR,
    question6           VARCHAR,
    answer6             VARCHAR,
    question7           VARCHAR,
    answer7             VARCHAR,
    question8           VARCHAR,
    answer8             VARCHAR,
    question9           VARCHAR,
    answer9             VARCHAR,
    question10          VARCHAR,
    answer10            VARCHAR
);
